#!/usr/bin/env python3
"""Validate the Markdown rule files and generate rules.json + the README index.

Part of the Apple Design Language rule set — Created by Edison Augustin X.

Usage:
    python3 rules/tools/build_rules.py          # validate, then write rules.json and README index
    python3 rules/tools/build_rules.py --check  # validate and fail if generated files are stale

Exit codes: 0 = OK, 1 = validation errors, 2 = generated files out of date (--check).
"""
from __future__ import annotations

import argparse
import json
import re
import sys
import unicodedata
from pathlib import Path

RULES_DIR = Path(__file__).resolve().parent.parent
REPO_ROOT = RULES_DIR.parent
GUIDELINES = REPO_ROOT / "GUIDELINES.md"
JSON_OUT = RULES_DIR / "rules.json"
README = RULES_DIR / "README.md"
INDEX_BEGIN = "<!-- BEGIN RULE INDEX (generated by rules/tools/build_rules.py — do not edit) -->"
INDEX_END = "<!-- END RULE INDEX -->"

SCHEMA_VERSION = "1.0.0"
PLATFORMS = ["iOS", "iPadOS", "macOS", "tvOS", "visionOS", "watchOS"]
LEVEL_TO_SEVERITY = {
    "MUST": "error",
    "MUST NOT": "error",
    "SHOULD": "warning",
    "SHOULD NOT": "warning",
    "MAY": "info",
}
CHECKS = {"hook", "review"}
PREFIXES = {
    "SYS": "Core",
    "SYNC": "Cross-platform sync",
    "LAY": "Layout",
    "GLS": "Materials and Liquid Glass",
    "COL": "Color and Dark Mode",
    "TYP": "Typography",
    "ICN": "Iconography",
    "MOT": "Motion",
    "HAP": "Haptics",
    "A11Y": "Accessibility",
    "WRT": "Writing",
    "L10N": "Localization",
    "NAV": "Navigation",
    "CMP": "Components",
    "PAT": "Patterns",
    "PRV": "Privacy",
    "AI": "Generative AI",
    "INP": "Inputs",
    "PLT-IOS": "Platform: iOS",
    "PLT-IPAD": "Platform: iPadOS",
    "PLT-DUO": "Platform: iPhone Duo",
    "PLT-MAC": "Platform: macOS",
    "PLT-TV": "Platform: tvOS",
    "PLT-VIS": "Platform: visionOS",
    "PLT-WATCH": "Platform: watchOS",
    "BRD": "Brand and legal",
    "STK": "Implementation stacks",
}
ID_RE = re.compile(r"^(?P<prefix>" + "|".join(sorted(map(re.escape, PREFIXES), key=len, reverse=True)) + r")-(?P<num>\d{2})$")
HEADING_RE = re.compile(r"^### (?P<id>\S+) · (?P<title>.+?)\s*$")
FIELD_RE = re.compile(r"^- \*\*(?P<key>[A-Za-z']+):\*\* (?P<value>.+?)\s*$")
LINK_RE = re.compile(r"\[(?P<text>[^\]]+)\]\((?P<url>[^)]+)\)")
XREF_RE = re.compile(r"\b(?:" + "|".join(sorted(map(re.escape, PREFIXES), key=len, reverse=True)) + r")-\d{2}\b")
REQUIRED = ["Level", "Severity", "Platforms", "Check", "Rule", "Source"]
OPTIONAL = ["Why", "Do", "Don't"]


def github_slug(heading: str) -> str:
    """Approximate GitHub's heading anchor algorithm."""
    text = heading.strip().lower()
    out = []
    for ch in text:
        if ch in " -":
            out.append("-" if ch == " " else ch)
        elif ch == "_" or ch.isalnum():
            out.append(ch)
        elif unicodedata.category(ch).startswith(("L", "N")):
            out.append(ch)
    return "".join(out)


def guideline_anchors() -> set[str]:
    text = GUIDELINES.read_text(encoding="utf-8")
    return {github_slug(h) for h in re.findall(r"^#{1,6} (.+)$", text, re.M)}


def parse_file(path: Path, errors: list[str]) -> list[dict]:
    rules: list[dict] = []
    current: dict | None = None
    for lineno, line in enumerate(path.read_text(encoding="utf-8").splitlines(), 1):
        heading = HEADING_RE.match(line)
        if heading:
            current = {"id": heading["id"], "title": heading["title"], "fields": {}, "file": path.name, "line": lineno}
            rules.append(current)
            continue
        if line.startswith("## ") or line.startswith("# "):
            current = None
            continue
        field = FIELD_RE.match(line)
        if field and current is not None:
            key = field["key"]
            if key in current["fields"]:
                errors.append(f"{path.name}:{lineno}: {current['id']} repeats field '{key}'")
            current["fields"][key] = field["value"]
    return rules


def validate(rule: dict, anchors: set[str], errors: list[str]) -> dict | None:
    where = f"{rule['file']}:{rule['line']} {rule['id']}"
    m = ID_RE.match(rule["id"])
    if not m:
        errors.append(f"{where}: invalid rule ID")
        return None
    f = rule["fields"]
    for key in REQUIRED:
        if key not in f:
            errors.append(f"{where}: missing required field '{key}'")
    unknown = set(f) - set(REQUIRED) - set(OPTIONAL)
    if unknown:
        errors.append(f"{where}: unknown field(s) {sorted(unknown)}")
    if any(key not in f for key in REQUIRED):
        return None

    level, severity = f["Level"], f["Severity"]
    if level not in LEVEL_TO_SEVERITY:
        errors.append(f"{where}: invalid level '{level}'")
    elif LEVEL_TO_SEVERITY[level] != severity:
        errors.append(f"{where}: level {level} requires severity '{LEVEL_TO_SEVERITY[level]}', found '{severity}'")
    if level in LEVEL_TO_SEVERITY and not re.match(rf"^{re.escape(level)}\b", f["Rule"]):
        errors.append(f"{where}: rule text must start with its level keyword '{level}'")

    if f["Check"] not in CHECKS:
        errors.append(f"{where}: check must be one of {sorted(CHECKS)}")

    if f["Platforms"] == "All":
        platforms = list(PLATFORMS)
    else:
        platforms = [p.strip() for p in f["Platforms"].split(",")]
        bad = [p for p in platforms if p not in PLATFORMS]
        if bad:
            errors.append(f"{where}: unknown platform(s) {bad}")

    sources = [{"title": s["text"], "url": s["url"]} for s in LINK_RE.finditer(f["Source"])]
    apple = [s for s in sources if s["url"].startswith("https://developer.apple.com/")]
    guide = [s for s in sources if s["url"].startswith("../GUIDELINES.md#")]
    if not apple:
        errors.append(f"{where}: needs at least one developer.apple.com source")
    if not guide:
        errors.append(f"{where}: needs a GUIDELINES.md section link")
    for s in guide:
        anchor = s["url"].split("#", 1)[1]
        if anchor not in anchors:
            errors.append(f"{where}: GUIDELINES anchor '#{anchor}' does not exist")

    return {
        "id": rule["id"],
        "prefix": m["prefix"],
        "number": int(m["num"]),
        "category": PREFIXES[m["prefix"]],
        "title": rule["title"],
        "level": level,
        "severity": severity,
        "platforms": platforms,
        "check": f["Check"],
        "rule": f["Rule"],
        "why": f.get("Why"),
        "do": f.get("Do"),
        "dont": f.get("Don't"),
        "sources": [{"title": s["title"], "url": s["url"].replace("../", "")} for s in sources],
        "file": f"rules/{rule['file']}",
    }


def build() -> tuple[list[dict], list[str]]:
    errors: list[str] = []
    anchors = guideline_anchors()
    raw: list[dict] = []
    files = sorted(p for p in RULES_DIR.glob("[0-9][0-9]-*.md"))
    if not files:
        errors.append("no rule files found")
    for path in files:
        raw.extend(parse_file(path, errors))

    rules = [r for r in (validate(r, anchors, errors) for r in raw) if r]

    seen: dict[str, str] = {}
    for r in rules:
        if r["id"] in seen:
            errors.append(f"duplicate ID {r['id']} in {r['file']} and {seen[r['id']]}")
        seen[r["id"]] = r["file"]

    by_prefix: dict[str, list[int]] = {}
    for r in rules:
        by_prefix.setdefault(r["prefix"], []).append(r["number"])
    for prefix, nums in by_prefix.items():
        if sorted(nums) != list(range(1, len(nums) + 1)):
            errors.append(f"{prefix}: rule numbers must run 01..{len(nums):02d} without gaps, found {sorted(nums)}")

    known = set(seen)
    for path in files:
        for lineno, line in enumerate(path.read_text(encoding="utf-8").splitlines(), 1):
            if HEADING_RE.match(line):
                continue
            for ref in XREF_RE.findall(line):
                if ref not in known:
                    errors.append(f"{path.name}:{lineno}: reference to unknown rule {ref}")

    rules.sort(key=lambda r: (list(PREFIXES).index(r["prefix"]), r["number"]))
    return rules, errors


def render_json(rules: list[dict]) -> str:
    counts = {
        "total": len(rules),
        "by_severity": {s: sum(r["severity"] == s for r in rules) for s in ("error", "warning", "info")},
        "by_check": {c: sum(r["check"] == c for r in rules) for c in sorted(CHECKS)},
    }
    doc = {
        "$schema_version": SCHEMA_VERSION,
        "name": "Apple Design Language rules",
        "author": "Edison Augustin X.",
        "description": "Enforceable rules for designing apps across the Apple ecosystem, derived from GUIDELINES.md and Apple's Human Interface Guidelines.",
        "generated_by": "rules/tools/build_rules.py",
        "levels": LEVEL_TO_SEVERITY,
        "categories": PREFIXES,
        "counts": counts,
        "rules": rules,
    }
    return json.dumps(doc, indent=2, ensure_ascii=False) + "\n"


def render_index(rules: list[dict]) -> str:
    lines = [
        INDEX_BEGIN,
        "",
        f"**{len(rules)} rules** · "
        f"{sum(r['severity'] == 'error' for r in rules)} error · "
        f"{sum(r['severity'] == 'warning' for r in rules)} warning · "
        f"{sum(r['severity'] == 'info' for r in rules)} info · "
        f"{sum(r['check'] == 'hook' for r in rules)} checked automatically by hooks",
        "",
        "| ID | Rule | Level | Platforms | Check |",
        "|---|---|---|---|---|",
    ]
    for r in rules:
        plats = "All" if r["platforms"] == PLATFORMS else ", ".join(r["platforms"])
        anchor = github_slug(f"{r['id']} · {r['title']}")
        lines.append(f"| [{r['id']}]({r['file'].replace('rules/', '')}#{anchor}) | {r['title']} | {r['level']} | {plats} | {r['check']} |")
    lines += ["", INDEX_END]
    return "\n".join(lines)


def replace_index(readme: str, index: str) -> str:
    pattern = re.compile(re.escape(INDEX_BEGIN) + r".*?" + re.escape(INDEX_END), re.S)
    if not pattern.search(readme):
        raise SystemExit(f"README.md is missing the index markers:\n{INDEX_BEGIN}\n{INDEX_END}")
    return pattern.sub(lambda _: index, readme)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true", help="fail if generated files are out of date")
    args = parser.parse_args()

    rules, errors = build()
    if errors:
        print(f"✗ {len(errors)} validation error(s):", file=sys.stderr)
        for e in errors:
            print(f"  - {e}", file=sys.stderr)
        return 1

    json_text = render_json(rules)
    readme_text = replace_index(README.read_text(encoding="utf-8"), render_index(rules))

    if args.check:
        stale = [p.name for p, t in ((JSON_OUT, json_text), (README, readme_text)) if not p.exists() or p.read_text(encoding="utf-8") != t]
        if stale:
            print(f"✗ generated files out of date: {', '.join(stale)} — run python3 rules/tools/build_rules.py", file=sys.stderr)
            return 2
        print(f"✓ {len(rules)} rules valid; generated files up to date")
        return 0

    JSON_OUT.write_text(json_text, encoding="utf-8")
    README.write_text(readme_text, encoding="utf-8")
    print(f"✓ {len(rules)} rules valid; wrote {JSON_OUT.relative_to(REPO_ROOT)} and README index")
    return 0


if __name__ == "__main__":
    sys.exit(main())
