// Apple Design Language — tokens for React Native
// Created by Edison Augustin X.
//
// GENERATED by skills/apple-design-language/scripts/build_tokens.py from assets/tokens.json.
// Do not edit by hand. Values: Apple Human Interface Guidelines, content current through September 2026.
//
// On iOS, colors are PlatformColor references to UIKit system colors: they adapt to light, dark, and
// Increase Contrast natively, like a SwiftUI or UIKit app (COL-01, COL-02). Elsewhere (Android, web) the
// system palette falls back to the HIG hex values for the current color scheme; semantic fallbacks are
// neutral project values, NOT Apple values. Text styles follow iOS Dynamic Type via dynamicTypeRamp.

import { Platform, PlatformColor, useColorScheme, type ColorValue, type TextProps, type TextStyle } from "react-native";

const palette = {
  red: { ios: "systemRed", light: "#FF383C", dark: "#FF4245" },
  orange: { ios: "systemOrange", light: "#FF8D28", dark: "#FF9230" },
  yellow: { ios: "systemYellow", light: "#FFCC00", dark: "#FFD600" },
  green: { ios: "systemGreen", light: "#34C759", dark: "#30D158" },
  mint: { ios: "systemMint", light: "#00C8B3", dark: "#00DAC3" },
  teal: { ios: "systemTeal", light: "#00C3D0", dark: "#00D2E0" },
  cyan: { ios: "systemCyan", light: "#00C0E8", dark: "#3CD3FE" },
  blue: { ios: "systemBlue", light: "#0088FF", dark: "#0091FF" },
  indigo: { ios: "systemIndigo", light: "#6155F5", dark: "#6D7CFF" },
  purple: { ios: "systemPurple", light: "#CB30E0", dark: "#DB34F2" },
  pink: { ios: "systemPink", light: "#FF2D55", dark: "#FF375F" },
  brown: { ios: "systemBrown", light: "#AC7F5E", dark: "#B78A66" },
  systemGray: { ios: "systemGray", light: "#8E8E93", dark: "#8E8E93" },
  systemGray2: { ios: "systemGray2", light: "#AEAEB2", dark: "#636366" },
  systemGray3: { ios: "systemGray3", light: "#C7C7CC", dark: "#48484A" },
  systemGray4: { ios: "systemGray4", light: "#D1D1D6", dark: "#3A3A3C" },
  systemGray5: { ios: "systemGray5", light: "#E5E5EA", dark: "#2C2C2E" },
  systemGray6: { ios: "systemGray6", light: "#F2F2F7", dark: "#1C1C1E" },
  label: { ios: "label", light: "#000000", dark: "#FFFFFF" },
  secondaryLabel: { ios: "secondaryLabel", light: "#8E8E93", dark: "#8E8E93" },
  background: { ios: "systemBackground", light: "#FFFFFF", dark: "#000000" },
  secondaryBackground: { ios: "secondarySystemBackground", light: "#F2F2F7", dark: "#1C1C1E" },
  groupedBackground: { ios: "systemGroupedBackground", light: "#F2F2F7", dark: "#000000" },
  separator: { ios: "separator", light: "#D1D1D6", dark: "#3A3A3C" },
  link: { ios: "link", light: "#0088FF", dark: "#0091FF" },
} as const;

export type NativeColorName = keyof typeof palette;

/** A system color: PlatformColor on iOS, the light or dark fallback elsewhere. */
export function systemColor(name: NativeColorName, scheme: "light" | "dark" = "light"): ColorValue {
  const c = palette[name];
  return Platform.OS === "ios" ? PlatformColor(c.ios) : c[scheme];
}

/** Every system color for the current appearance. On iOS the values adapt natively without re-rendering. */
export function useSystemColors(): Record<NativeColorName, ColorValue> {
  const scheme = useColorScheme() === "dark" ? "dark" : "light";
  const out = {} as Record<NativeColorName, ColorValue>;
  for (const name of Object.keys(palette) as NativeColorName[]) out[name] = systemColor(name, scheme);
  return out;
}

/** iOS text styles (Large default size). Keep allowFontScaling on (the default) so Dynamic Type applies (TYP-01). */
export const textStyles = {
  largeTitle: { fontSize: 34, lineHeight: 41, fontWeight: "400" },
  title1: { fontSize: 28, lineHeight: 34, fontWeight: "400" },
  title2: { fontSize: 22, lineHeight: 28, fontWeight: "400" },
  title3: { fontSize: 20, lineHeight: 25, fontWeight: "400" },
  headline: { fontSize: 17, lineHeight: 22, fontWeight: "600" },
  body: { fontSize: 17, lineHeight: 22, fontWeight: "400" },
  callout: { fontSize: 16, lineHeight: 21, fontWeight: "400" },
  subheadline: { fontSize: 15, lineHeight: 20, fontWeight: "400" },
  footnote: { fontSize: 13, lineHeight: 18, fontWeight: "400" },
  caption1: { fontSize: 12, lineHeight: 16, fontWeight: "400" },
  caption2: { fontSize: 11, lineHeight: 13, fontWeight: "400" },
} satisfies Record<string, TextStyle>;

export type TextStyleName = keyof typeof textStyles;

/** The matching iOS Dynamic Type ramp for each text style — pass it as <Text dynamicTypeRamp={…}>. */
export const dynamicTypeRamp = {
  largeTitle: "largeTitle",
  title1: "title1",
  title2: "title2",
  title3: "title3",
  headline: "headline",
  body: "body",
  callout: "callout",
  subheadline: "subheadline",
  footnote: "footnote",
  caption1: "caption1",
  caption2: "caption2",
} as const satisfies Record<TextStyleName, NonNullable<TextProps["dynamicTypeRamp"]>>;

/** Minimum hit target in points (A11Y-01): 44 on iPhone and iPad; use hitSlop to reach it around small visuals. */
export const minimumHitTarget = 44;
/** Minimum text size on iOS, in points (TYP-02). */
export const minimumTextSize = 11;
