// Apple Design Language — tokens for JavaScript and TypeScript (React, Next.js, Vue, Svelte, plain JS)
// Created by Edison Augustin X.
//
// GENERATED by skills/apple-design-language/scripts/build_tokens.py from assets/tokens.json.
// Do not edit by hand. Values: Apple Human Interface Guidelines, content current through September 2026.
//
// Import tokens.css once; then use `color`, `text`, … in inline styles or CSS-in-JS. They are CSS variable
// references, so light, dark, and Increase Contrast switch automatically (COL-01, COL-02, COL-07).
// Use `resolveSystemColor` only where CSS variables can't reach (canvas, WebGL, generated images).

export type ColorVariants = {
  light: string;
  dark: string;
  lightIncreasedContrast: string;
  darkIncreasedContrast: string;
};

export const systemColorNames = ["red", "orange", "yellow", "green", "mint", "teal", "cyan", "blue", "indigo", "purple", "pink", "brown", "systemGray", "systemGray2", "systemGray3", "systemGray4", "systemGray5", "systemGray6"] as const;
export type SystemColorName = (typeof systemColorNames)[number];

/** HIG system color values: light, dark, and increased-contrast variants. */
export const systemColors: Record<SystemColorName, ColorVariants> = {
  red: { light: "#FF383C", dark: "#FF4245", lightIncreasedContrast: "#E9152D", darkIncreasedContrast: "#FF6165" },
  orange: { light: "#FF8D28", dark: "#FF9230", lightIncreasedContrast: "#C55300", darkIncreasedContrast: "#FFA056" },
  yellow: { light: "#FFCC00", dark: "#FFD600", lightIncreasedContrast: "#A16A00", darkIncreasedContrast: "#FEDF43" },
  green: { light: "#34C759", dark: "#30D158", lightIncreasedContrast: "#008932", darkIncreasedContrast: "#4AD968" },
  mint: { light: "#00C8B3", dark: "#00DAC3", lightIncreasedContrast: "#008575", darkIncreasedContrast: "#54DFCB" },
  teal: { light: "#00C3D0", dark: "#00D2E0", lightIncreasedContrast: "#008198", darkIncreasedContrast: "#3BDDEC" },
  cyan: { light: "#00C0E8", dark: "#3CD3FE", lightIncreasedContrast: "#007EAE", darkIncreasedContrast: "#6DD9FF" },
  blue: { light: "#0088FF", dark: "#0091FF", lightIncreasedContrast: "#1E6EF4", darkIncreasedContrast: "#5CB8FF" },
  indigo: { light: "#6155F5", dark: "#6D7CFF", lightIncreasedContrast: "#564ADE", darkIncreasedContrast: "#A7AAFF" },
  purple: { light: "#CB30E0", dark: "#DB34F2", lightIncreasedContrast: "#B02FC2", darkIncreasedContrast: "#EA8DFF" },
  pink: { light: "#FF2D55", dark: "#FF375F", lightIncreasedContrast: "#E7124D", darkIncreasedContrast: "#FF8AC4" },
  brown: { light: "#AC7F5E", dark: "#B78A66", lightIncreasedContrast: "#956D51", darkIncreasedContrast: "#DBA679" },
  systemGray: { light: "#8E8E93", dark: "#8E8E93", lightIncreasedContrast: "#6C6C70", darkIncreasedContrast: "#AEAEB2" },
  systemGray2: { light: "#AEAEB2", dark: "#636366", lightIncreasedContrast: "#8E8E93", darkIncreasedContrast: "#7C7C80" },
  systemGray3: { light: "#C7C7CC", dark: "#48484A", lightIncreasedContrast: "#AEAEB2", darkIncreasedContrast: "#545456" },
  systemGray4: { light: "#D1D1D6", dark: "#3A3A3C", lightIncreasedContrast: "#BCBCC0", darkIncreasedContrast: "#444446" },
  systemGray5: { light: "#E5E5EA", dark: "#2C2C2E", lightIncreasedContrast: "#D8D8DC", darkIncreasedContrast: "#363638" },
  systemGray6: { light: "#F2F2F7", dark: "#1C1C1E", lightIncreasedContrast: "#EBEBF0", darkIncreasedContrast: "#242426" },
};

/** CSS variable references from tokens.css — they follow the system appearance and contrast settings. */
export const color = {
  red: "var(--adl-red)",
  orange: "var(--adl-orange)",
  yellow: "var(--adl-yellow)",
  green: "var(--adl-green)",
  mint: "var(--adl-mint)",
  teal: "var(--adl-teal)",
  cyan: "var(--adl-cyan)",
  blue: "var(--adl-blue)",
  indigo: "var(--adl-indigo)",
  purple: "var(--adl-purple)",
  pink: "var(--adl-pink)",
  brown: "var(--adl-brown)",
  systemGray: "var(--adl-system-gray)",
  systemGray2: "var(--adl-system-gray2)",
  systemGray3: "var(--adl-system-gray3)",
  systemGray4: "var(--adl-system-gray4)",
  systemGray5: "var(--adl-system-gray5)",
  systemGray6: "var(--adl-system-gray6)",
  accent: "var(--adl-accent)",
  destructive: "var(--adl-destructive)",
  background: "var(--adl-background)",
  label: "var(--adl-label)",
  secondaryLabel: "var(--adl-secondary-label)",
  backgroundGrouped: "var(--adl-background-grouped)",
  backgroundGroupedRow: "var(--adl-background-grouped-row)",
  separator: "var(--adl-separator)",
  fill: "var(--adl-fill)",
  onAccent: "var(--adl-on-accent)",
  accentText: "var(--adl-accent-text)",
  destructiveText: "var(--adl-destructive-text)",
  accentFill: "var(--adl-accent-fill)",
} as const;
export type ColorToken = keyof typeof color;

/** System font stacks. Never bundle Apple system fonts (TYP-04). */
export const font = {
  text: "var(--adl-font-text)",
  rounded: "var(--adl-font-rounded)",
  serif: "var(--adl-font-serif)",
  mono: "var(--adl-font-mono)",
} as const;

/** iOS text styles at the Large (default) Dynamic Type size, as style objects (rem-based, so they scale). */
export const text = {
  largeTitle: { fontSize: "var(--adl-text-large-title-size)", lineHeight: "var(--adl-text-large-title-line-height)", fontWeight: "var(--adl-text-large-title-weight)" },
  title1: { fontSize: "var(--adl-text-title1-size)", lineHeight: "var(--adl-text-title1-line-height)", fontWeight: "var(--adl-text-title1-weight)" },
  title2: { fontSize: "var(--adl-text-title2-size)", lineHeight: "var(--adl-text-title2-line-height)", fontWeight: "var(--adl-text-title2-weight)" },
  title3: { fontSize: "var(--adl-text-title3-size)", lineHeight: "var(--adl-text-title3-line-height)", fontWeight: "var(--adl-text-title3-weight)" },
  headline: { fontSize: "var(--adl-text-headline-size)", lineHeight: "var(--adl-text-headline-line-height)", fontWeight: "var(--adl-text-headline-weight)" },
  body: { fontSize: "var(--adl-text-body-size)", lineHeight: "var(--adl-text-body-line-height)", fontWeight: "var(--adl-text-body-weight)" },
  callout: { fontSize: "var(--adl-text-callout-size)", lineHeight: "var(--adl-text-callout-line-height)", fontWeight: "var(--adl-text-callout-weight)" },
  subheadline: { fontSize: "var(--adl-text-subheadline-size)", lineHeight: "var(--adl-text-subheadline-line-height)", fontWeight: "var(--adl-text-subheadline-weight)" },
  footnote: { fontSize: "var(--adl-text-footnote-size)", lineHeight: "var(--adl-text-footnote-line-height)", fontWeight: "var(--adl-text-footnote-weight)" },
  caption1: { fontSize: "var(--adl-text-caption1-size)", lineHeight: "var(--adl-text-caption1-line-height)", fontWeight: "var(--adl-text-caption1-weight)" },
  caption2: { fontSize: "var(--adl-text-caption2-size)", lineHeight: "var(--adl-text-caption2-line-height)", fontWeight: "var(--adl-text-caption2-weight)" },
} as const;
export type TextStyle = keyof typeof text;

/** The same text styles in points (1 CSS px ≈ 1 pt on Apple devices at default zoom). */
export const textStylePoints: Record<TextStyle, { size: number; leading: number; weight: number; emphasizedWeight: number }> = {
  largeTitle: { size: 34, leading: 41, weight: 400, emphasizedWeight: 700 },
  title1: { size: 28, leading: 34, weight: 400, emphasizedWeight: 700 },
  title2: { size: 22, leading: 28, weight: 400, emphasizedWeight: 700 },
  title3: { size: 20, leading: 25, weight: 400, emphasizedWeight: 600 },
  headline: { size: 17, leading: 22, weight: 600, emphasizedWeight: 600 },
  body: { size: 17, leading: 22, weight: 400, emphasizedWeight: 600 },
  callout: { size: 16, leading: 21, weight: 400, emphasizedWeight: 600 },
  subheadline: { size: 15, leading: 20, weight: 400, emphasizedWeight: 600 },
  footnote: { size: 13, leading: 18, weight: 400, emphasizedWeight: 600 },
  caption1: { size: 12, leading: 16, weight: 400, emphasizedWeight: 600 },
  caption2: { size: 11, leading: 13, weight: 400, emphasizedWeight: 600 },
};

/** Default and minimum text sizes per platform, in points (TYP-02). */
export const textSize = {
  ios: { default: 17, minimum: 11 },
  ipados: { default: 17, minimum: 11 },
  macos: { default: 13, minimum: 10 },
  tvos: { default: 29, minimum: 23 },
  visionos: { default: 17, minimum: 12 },
  watchos: { default: 16, minimum: 12 },
} as const;

/** Hit targets per platform, in points (A11Y-01). Web default: 44 px everywhere. */
export const hitTarget = {
  ios: { default: 44, minimum: 28 },
  ipados: { default: 44, minimum: 28 },
  macos: { default: 28, minimum: 20 },
  tvos: { default: 66, minimum: 56 },
  visionos: { default: 60, minimum: 28 },
  watchos: { default: 44, minimum: 28 },
} as const;

/** Layout variables from tokens.css. */
export const layout = {
  controlSize: "var(--adl-control-size)",
  safeTop: "var(--adl-safe-top)",
  safeRight: "var(--adl-safe-right)",
  safeBottom: "var(--adl-safe-bottom)",
  safeLeft: "var(--adl-safe-left)",
} as const;

/** Motion variables from tokens.css (1 ms under Reduce Motion — MOT-02). Project defaults, not Apple values. */
export const motion = {
  duration: "var(--adl-motion-duration)",
  easing: "var(--adl-motion-easing)",
} as const;

/** Hex value of a system color for an appearance — for canvas, WebGL, and image generation only. */
export function resolveSystemColor(
  name: SystemColorName,
  options: { dark?: boolean; increasedContrast?: boolean } = {},
): string {
  const c = systemColors[name];
  if (options.increasedContrast) return options.dark ? c.darkIncreasedContrast : c.lightIncreasedContrast;
  return options.dark ? c.dark : c.light;
}
